# Default config for sraft server
Id: First
HeartbeatTimeoutBaseTime: 250000000
HeartbeatTimeoutRandRange: 50000000
LogConfig:
  DisableTimestamp: false
  DisableColor: false
  FullTimestamp: true
  Level: Trace
  TimestampFormat: "2006-01-02T15:04:05Z07:00"

## ======================== Server point config
PointKind: http_v1
PointConfig:
  config:
    Point: 127.0.0.1:3001

## ======================== Data storage configs

## DataStorageKind, to specify how to storage the data.
##
## Data storage kinds:
## memory_v1: Quick and data not safe on machine.
DataStorageKind: memory_v1

## DataStoragePath define the data path in storage. Default is _data.
DataStoragePath: _data

## Different storage has different configs, for more detail, see TODO
DataStorageConfig:
  Empty: empty

## ======================== Log storage configs

## See config: [DataStorageKind]
LogsStorageKind: memory_v1
## See config: [DataStoragePath]
LogsStoragePath: _log

### ======================== Cluster config info
ClusterConfig:
  ClusterElement:
    - Id: Second
      Kind: http_v1
      ClientConfig:
        Config:
          TargetPoint: http://127.0.0.1:3002
    - Id: First
      Kind: http_v1
      ClientConfig:
        Config:
          TargetPoint: http://127.0.0.1:3001